### ISSUE TITLE
Why does input.json have my email?

### ISSUE THREAD

**Issue by beingmohit** [RichardLitt/shim-input#1]
Why does input.json have my email?

Can you please remove it !

**Comment by RichardLitt** [comment]
You committed, opened an issue, or otherwise interfaced with the organization or repo I was looking at. It wasn't targeted specifically. In any case, removed, added a short README. 

Your email is still in the public domain on GitHub in your old commits. If you're interested in removing it from things, I would suggest contacting GitHub.
